### ISSUE TITLE
Crash GPT-J on mGPU

### ISSUE THREAD

**Issue by daemyung** [triton-inference-server/fastertransformer_backend#40]
### Description

Additional information: Running on single GPU is fine.

```shell
NVIDIA-SMI 510.85.02
Driver Version: 510.85.02
CUDA Version: 11.7 
Tesla V100-SXM2-32GB
triton_with_ft:22.07


/workspace/tools/identity_test.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([input_start_ids.shape[0], 1]).astype(np.bool)
set request
W0902 08:44:50.026851 940 libfastertransformer.cc:1647] model fastertransformer, instance fastertransformer_0, executing 1 requests
W0902 08:44:50.026892 940 libfastertransformer.cc:812] TRITONBACKEND_ModelExecute: Running fastertransformer_0 with 1 requests
W0902 08:44:50.026904 940 libfastertransformer.cc:886] get total batch_size = 8
W0902 08:44:50.026919 940 libfastertransformer.cc:1296] get input count = 16
W0902 08:44:50.026935 940 libfastertransformer.cc:1368] collect name: start_id size: 32 bytes
W0902 08:44:50.026946 940 libfastertransformer.cc:1368] collect name: input_ids size: 704 bytes
W0902 08:44:50.026954 940 libfastertransformer.cc:1368] collect name: bad_words_list size: 64 bytes
W0902 08:44:50.026965 940 libfastertransformer.cc:1368] collect name: random_seed size: 64 bytes
W0902 08:44:50.026973 940 libfastertransformer.cc:1368] collect name: end_id size: 32 bytes
W0902 08:44:50.026981 940 libfastertransformer.cc:1368] collect name: input_lengths size: 32 bytes
W0902 08:44:50.026990 940 libfastertransformer.cc:1368] collect name: request_output_len size: 32 bytes
W0902 08:44:50.026998 940 libfastertransformer.cc:1368] collect name: runtime_top_k size: 32 bytes
W0902 08:44:50.027005 940 libfastertransformer.cc:1368] collect name: runtime_top_p size: 32 bytes
W0902 08:44:50.027013 940 libfastertransformer.cc:1368] collect name: temperature size: 32 bytes
W0902 08:44:50.027020 940 libfastertransformer.cc:1368] collect name: len_penalty size: 32 bytes
W0902 08:44:50.027031 940 libfastertransformer.cc:1368] collect name: is_return_log_probs size: 8 bytes
W0902 08:44:50.027042 940 libfastertransformer.cc:1368] collect name: stop_words_list size: 64 bytes
W0902 08:44:50.027053 940 libfastertransformer.cc:1368] collect name: beam_width size: 32 bytes
W0902 08:44:50.027066 940 libfastertransformer.cc:1368] collect name: beam_search_diversity_rate size: 32 bytes
W0902 08:44:50.027078 940 libfastertransformer.cc:1368] collect name: repetition_penalty size: 32 bytes
W0902 08:44:50.027088 940 libfastertransformer.cc:1379] the data is in CPU
W0902 08:44:50.027094 940 libfastertransformer.cc:1386] the data is in CPU
W0902 08:44:50.027163 940 libfastertransformer.cc:1244] before ThreadForward 0
W0902 08:44:50.027288 940 libfastertransformer.cc:1252] after ThreadForward 0
W0902 08:44:50.027302 940 libfastertransformer.cc:1244] before ThreadForward 1
W0902 08:44:50.027357 940 libfastertransformer.cc:1252] after ThreadForward 1
I0902 08:44:50.027371 940 libfastertransformer.cc:1090] Start to forward
I0902 08:44:50.027407 940 libfastertransformer.cc:1090] Start to forward
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
Signal (  what():  [FT][ERROR] CUDA runtime error: an illegal memory access was encountered /workspace/build/fastertransformer_backend/build/_deps/repo-ft-src/src/fastertransformer/utils/memory_utils.cu:96

6) received.
Signal (6) received.
 0# 0x000055C3734BAC19 in /opt/tritonserver/bin/tritonserver
 1# 0x00007FA6EEF99090 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# 0x00007FA6EF36053A in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007FA6EF35E38C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007FA6EF35E3F7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007FA6EF35E6A9 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007FA63CFEC37D in /opt/tritonserver/backends/fastertransformer/libtransformer-shared.so
 9# fastertransformer::invokeLengthCriterion(bool*, bool*, int*, unsigned int const*, int, int, int, CUstream_st*) in /opt/tritonserver/backends/fastertransformer/libtransformer-shared.so
10# fastertransformer::DynamicDecodeLayer<float>::forward(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fastertransformer::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, fastertransformer::Tensor> > >*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fastertransformer::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, fastertransformer::Tensor> > > const*) in /opt/tritonserver/backends/fastertransformer/libtransformer-shared.so
11# fastertransformer::GptJ<__half>::forward(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fastertransformer::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, fastertransformer::Tensor> > >*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fastertransformer::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, fastertransformer::Tensor> > > const*, fastertransformer::GptJWeight<__half> const*) in /opt/tritonserver/backends/fastertransformer/libtransformer-shared.so
12# GptJTritonModelInstance<__half>::forward(std::shared_ptr<std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, triton::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, triton::Tensor> > > >) in /opt/tritonserver/backends/fastertransformer/libtransformer-shared.so
13# 0x00007FA6E4434C5A in /opt/tritonserver/backends/fastertransformer/libtriton_fastertransformer.so
14# 0x00007FA6EF38ADE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
15# 0x00007FA6F059F609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
16# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/connectionpool.py", line 163, in get_socket
    return self._socket_queue.get(block=False)
  File "src/gevent/queue.py", line 335, in gevent._gevent_cqueue.Queue.get
  File "src/gevent/queue.py", line 350, in gevent._gevent_cqueue.Queue.get
  File "src/gevent/queue.py", line 319, in gevent._gevent_cqueue.Queue._Queue__get_or_peek

_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/tools/identity_test.py", line 273, in <module>
    send_requests(FLAGS.url, FLAGS.batch_size, input_start_ids,
  File "/workspace/tools/identity_test.py", line 136, in send_requests
    result = client.infer(model_name, inputs)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1414, in infer
    response = self._post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 309, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 226, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/connectionpool.py", line 166, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/connectionpool.py", line 127, in _create_socket
    raise first_error
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/connectionpool.py", line 114, in _create_socket
    sock = self._connect_socket(sock, sock_info[-1])
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/connectionpool.py", line 136, in _connect_socket
    sock.connect(address)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused
root@3acd604a7360:/workspace# --------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node 3acd604a7360 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
```


### Reproduced Steps

```shell
Step to reproduce:
1. cd fasttransformer_backend
2. export WORKSPACE=$(pwd)
3. docker run -it \
    --gpus all \
    -v ${WORKSPACE}:/workspace \
    -p 8000:8000 \
    -p 8001:8001 \
    -p 8002:8002 \
    --shm-size=2G \
    --name ft \
    triton_with_ft:22.07 bash
4. CUDA_VISIBLE_DEVICES=0,1 mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver \
    --model-repository=/workspace/all_models/gptj
5. python3 /workspace/tools/identity_test.py
```

**Comment by byshiue** [comment]
Can you provide the log when you launch the server?

**Comment by byshiue** [comment]
Do you use latest main branch? The dimension setting of bad_words_list and stop_words_list are wrong in your config.pbtxt.

**Comment by daemyung** [comment]
@byshiue Yes I'm using and I modified config.pbtxt file. I reverted my changes but still this crash is happened.

**Comment by daemyung** [comment]
@byshiue Could I know your test machine?

**Comment by byshiue** [comment]
> @byshiue Could I know your test machine?

I have verified on both A100 and V100 and I don't encounter issue for both environments.

**Comment by daemyung** [comment]
@byshiue Ok I will. It's very strange. Only V100 has this problem. Do you know any clues for this issue?

**Comment by daemyung** [comment]
@byshiue Please check [debug_logs.txt](https://github.com/triton-inference-server/fastertransformer_backend/files/9501788/debug_logs.txt).

**Comment by byshiue** [comment]
This is issue of https://github.com/triton-inference-server/fastertransformer_backend/issues/41, but not issue for multi-GPU.

**Comment by daemyung** [comment]
@byshiue Right! This isn't mGPU issue. I will close this issue.
